### ISSUE TITLE
Recipe broken with conda 4.7.5

### ISSUE THREAD

**Issue by borupdaniel** [conda-forge/gpi-feedstock#4] opened 2019-06-26 21:34 UTC
The most recent version of this recipe built with no errors two days ago. When I try to run a local docker build I get a test failure even when using the same recipe as before. I suspect this is related to conda 4.7.5 since it was released last night and appears to be the only minor version change in the initial environment setup. 

Possibly this shares something in common with conda-forge/staged-recipes#8623 (particularly the large number of clobber warnings with a "None" source path). @conda-forge/core if you have a moment, could you take a look and see if this is indeed related or caused by something else?

Previously, testing worked fine and the output in the test section was the following:
<details>

```
TEST START: /home/conda/feedstock_root/build_artifacts/linux-64/gpi-1.0.6-py36_1.tar.bz2
INFO:conda_build.variants:Adding in variants from /tmp/tmpmw52z2u1/info/recipe/conda_build_config.yaml
Adding in variants from /tmp/tmpmw52z2u1/info/recipe/conda_build_config.yaml
Renaming work directory,  /home/conda/feedstock_root/build_artifacts/gpi_1561386517571/work  to  /home/conda/feedstock_root/build_artifacts/gpi_1561386517571/work_moved_gpi-1.0.6-py36_1_linux-64
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/conda/feedstock_root/build_artifacts/gpi_1561386517571/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl


The following NEW packages will be INSTALLED:

    ca-certificates:  2019.6.16-hecc5488_0          conda-forge
    eigen:            3.3.7-h6bb024c_1000           conda-forge
    fftw:             3.3.8-nompi_h7f3a6c3_1105     conda-forge
    fontconfig:       2.13.1-he4413a7_1000          conda-forge
    freetype:         2.10.0-he983fc9_0             conda-forge
    gpi:              1.0.6-py36_1                  local      
    h5py:             2.9.0-nompi_py36hf008753_1102 conda-forge
    hdf5:             1.10.4-nompi_h3c11f04_1106    conda-forge
    icu:              58.2-hf484d3e_1000            conda-forge
    jpeg:             9c-h14c3975_1001              conda-forge
    libblas:          3.8.0-7_openblas              conda-forge
    libcblas:         3.8.0-7_openblas              conda-forge
    libffi:           3.2.1-he1b5a44_1006           conda-forge
    libgcc-ng:        9.1.0-hdf63c60_0              defaults   
    libgfortran-ng:   7.3.0-hdf63c60_0              defaults   
    libiconv:         1.15-h516909a_1005            conda-forge
    liblapack:        3.8.0-7_openblas              conda-forge
    libpng:           1.6.37-hed695b0_0             conda-forge
    libstdcxx-ng:     9.1.0-hdf63c60_0              defaults   
    libtiff:          4.0.10-h57b8799_1003          conda-forge
    libuuid:          2.32.1-h14c3975_1000          conda-forge
    libxcb:           1.13-h14c3975_1002            conda-forge
    libxml2:          2.9.9-h13577e0_0              conda-forge
    lz4-c:            1.8.3-he1b5a44_1001           conda-forge
    ncurses:          6.1-hf484d3e_1002             conda-forge
    numpy:            1.16.4-py36h95a1406_0         conda-forge
    olefile:          0.46-py_0                     conda-forge
    openblas:         0.3.5-h9ac9557_1001           conda-forge
    openssl:          1.1.1b-h14c3975_1             conda-forge
    pillow:           6.0.0-py36he7afcd5_0          conda-forge
    psutil:           5.6.3-py36h516909a_0          conda-forge
    pthread-stubs:    0.4-h14c3975_1001             conda-forge
    pyopengl:         3.1.3b2-py_1                  conda-forge
    pyqt:             4.11.4-py36_3                 conda-forge
    python:           3.6.7-h381d211_1004           conda-forge
    qimage2ndarray:   1.7-py_0                      conda-forge
    qt:               4.8.7-2                       defaults   
    readline:         7.0-hf8c457e_1001             conda-forge
    sip:              4.18-py36_1                   conda-forge
    six:              1.12.0-py36_1000              conda-forge
    sqlite:           3.28.0-h8b20d00_0             conda-forge
    tk:               8.6.9-hed695b0_1002           conda-forge
    xorg-kbproto:     1.0.7-h14c3975_1002           conda-forge
    xorg-libice:      1.0.9-h516909a_1004           conda-forge
    xorg-libsm:       1.2.3-h84519dc_1000           conda-forge
    xorg-libx11:      1.6.7-h14c3975_1000           conda-forge
    xorg-libxau:      1.0.9-h14c3975_0              conda-forge
    xorg-libxdmcp:    1.1.3-h516909a_0              conda-forge
    xorg-libxrender:  0.9.10-h516909a_1002          conda-forge
    xorg-renderproto: 0.11.1-h14c3975_1002          conda-forge
    xorg-xproto:      7.0.31-h14c3975_1007          conda-forge
    xz:               5.2.4-h14c3975_1001           conda-forge
    zlib:             1.2.11-h14c3975_1004          conda-forge
    zstd:             1.4.0-h3b9ef0a_0              conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/home/conda/feedstock_root/build_artifacts/gpi_1561386517571/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/gpi_1561386517571/test_tmp
import: 'gpi'
GPI 1.0.6 (2019-06-24)  Copyright (C) 2014 Dignity Health
This program comes with ABSOLUTELY NO WARRANTY; see the LICENSE for details.

    NO CLINICAL USE.  THE SOFTWARE IS NOT INTENDED FOR COMMERCIAL PURPOSES
AND SHOULD BE USED ONLY FOR NON-COMMERCIAL RESEARCH PURPOSES.  THE SOFTWARE
MAY NOT IN ANY EVENT BE USED FOR ANY CLINICAL OR DIAGNOSTIC PURPOSES.  YOU
ACKNOWLEDGE AND AGREE THAT THE SOFTWARE IS NOT INTENDED FOR USE IN ANY HIGH
RISK OR STRICT LIABILITY ACTIVITY, INCLUDING BUT NOT LIMITED TO LIFE SUPPORT
OR EMERGENCY MEDICAL OPERATIONS OR USES.  LICENSOR MAKES NO WARRANTY AND HAS
NO LIABILITY ARISING FROM ANY USE OF THE SOFTWARE IN ANY HIGH RISK OR STRICT
LIABILITY ACTIVITIES.

import: 'gpi'
+ DISPLAY=localhost:1.0
+ xvfb-run -a bash -c 'gpi --help'
GPI 1.0.6 (2019-06-24)  Copyright (C) 2014 Dignity Health
This program comes with ABSOLUTELY NO WARRANTY; see the LICENSE for details.

    NO CLINICAL USE.  THE SOFTWARE IS NOT INTENDED FOR COMMERCIAL PURPOSES
AND SHOULD BE USED ONLY FOR NON-COMMERCIAL RESEARCH PURPOSES.  THE SOFTWARE
MAY NOT IN ANY EVENT BE USED FOR ANY CLINICAL OR DIAGNOSTIC PURPOSES.  YOU
ACKNOWLEDGE AND AGREE THAT THE SOFTWARE IS NOT INTENDED FOR USE IN ANY HIGH
RISK OR STRICT LIABILITY ACTIVITY, INCLUDING BUT NOT LIMITED TO LIFE SUPPORT
OR EMERGENCY MEDICAL OPERATIONS OR USES.  LICENSOR MAKES NO WARRANTY AND HAS
NO LIABILITY ARISING FROM ANY USE OF THE SOFTWARE IN ANY HIGH RISK OR STRICT
LIABILITY ACTIVITIES.

Usage: gpi [options]

Options:
  -h, --help            show this help message and exit
  --config              GPI will read the User ENV and config file and dump
                        the parsed info to stdout.
  --log=LOGLEVEL        Change the output level of the logger: debug, info,
                        node, warn, error, and critical
  --nogui               causes GPI to run without a GUI for scripting.
                        Requires a network file.  The --script option is
                        implied.
  --script              causes GPI to terminate after the supplied network is
                        finished executing.  Requires a network file.
  -s STRING, --string=STRING
                        passes a string arg to a String-node by label.
                        Handles multiple args.  Syntax: -s
                        <label1>:<string/path> -s <label2>:<string/path>.
  --specs               GPI will create a platform specs file and exit.
  --defines             Show some internally used defines, such as temp
                        directory paths.
  --nosplash            Skip the splash screen.
+ exit 0

Resource usage statistics from testing gpi:
   Process count: 5
   CPU time: unavailable
   Memory: 32.7M
   Disk usage: 20B
   Time elapsed: 0:00:04.1

TEST END: /home/conda/feedstock_root/build_artifacts/linux-64/gpi-1.0.6-py36_1.tar.bz2
```
</details>

Now I get the following output, which includes a large number of clobber warnings (I've removed most of them for space) and ends with a failed import of qtWebKit.

Full output:
<details> 

```
TEST START: /home/conda/feedstock_root/build_artifacts/linux-64/gpi-1.0.6-py36_1.tar.bz2
Adding in variants from /tmp/tmpt6t0ys3n/info/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /tmp/tmpt6t0ys3n/info/recipe/conda_build_config.yaml
INFO conda_build.variants:_combine_spec_dictionaries(189): Adding in variants from /tmp/tmpt6t0ys3n/info/recipe/conda_build_config.yaml
Renaming work directory,  /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/work  to  /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/work_moved_gpi-1.0.6-py36_1_linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl


The following NEW packages will be INSTALLED:

    ca-certificates:  2019.6.16-hecc5488_0          conda-forge
    cairo:            1.14.6-4                      conda-forge
    eigen:            3.3.7-h6bb024c_1000           conda-forge
    expat:            2.2.5-he1b5a44_1003           conda-forge
    fftw:             3.3.8-nompi_h7f3a6c3_1105     conda-forge
    fontconfig:       2.12.1-4                      conda-forge
    freetype:         2.7-1                         conda-forge
    gettext:          0.19.8.1-hc5be6a0_1002        conda-forge
    glib:             2.51.4-0                      conda-forge
    gpi:              1.0.6-py36_1                  local      
    graphite2:        1.3.13-hf484d3e_1000          conda-forge
    h5py:             2.9.0-nompi_py36hf008753_1102 conda-forge
    harfbuzz:         1.4.3-0                       conda-forge
    hdf5:             1.10.4-nompi_h3c11f04_1106    conda-forge
    icu:              58.2-hf484d3e_1000            conda-forge
    jpeg:             9c-h14c3975_1001              conda-forge
    libblas:          3.8.0-7_openblas              conda-forge
    libcblas:         3.8.0-7_openblas              conda-forge
    libffi:           3.2.1-he1b5a44_1006           conda-forge
    libgcc-ng:        9.1.0-hdf63c60_0              defaults   
    libgfortran-ng:   7.3.0-hdf63c60_0              defaults   
    libiconv:         1.15-h516909a_1005            conda-forge
    liblapack:        3.8.0-7_openblas              conda-forge
    libpng:           1.6.37-hed695b0_0             conda-forge
    libstdcxx-ng:     9.1.0-hdf63c60_0              defaults   
    libtiff:          4.0.10-h57b8799_1003          conda-forge
    libuuid:          2.32.1-h14c3975_1000          conda-forge
    libxcb:           1.13-h14c3975_1002            conda-forge
    libxml2:          2.9.9-h13577e0_0              conda-forge
    lz4-c:            1.8.3-he1b5a44_1001           conda-forge
    ncurses:          6.1-hf484d3e_1002             conda-forge
    numpy:            1.16.4-py36h95a1406_0         conda-forge
    olefile:          0.46-py_0                     conda-forge
    openblas:         0.3.5-h9ac9557_1001           conda-forge
    openssl:          1.0.2r-h14c3975_0             conda-forge
    pango:            1.40.4-0                      conda-forge
    pcre:             8.41-hf484d3e_1003            conda-forge
    pillow:           4.2.1-py36_0                  conda-forge
    pixman:           0.34.0-h14c3975_1003          conda-forge
    psutil:           5.6.3-py36h516909a_0          conda-forge
    pthread-stubs:    0.4-h14c3975_1001             conda-forge
    pyopengl:         3.1.3b2-py_1                  conda-forge
    pyqt:             4.11.4-py36_3                 conda-forge
    python:           3.6.7-hd21baee_1002           conda-forge
    qimage2ndarray:   1.7-py_0                      conda-forge
    qt:               4.8.7-ha8c56c7_9              conda-forge
    readline:         7.0-hf8c457e_1001             conda-forge
    sip:              4.18-py36_1                   conda-forge
    six:              1.12.0-py36_1000              conda-forge
    sqlite:           3.28.0-h8b20d00_0             conda-forge
    tk:               8.6.9-hed695b0_1002           conda-forge
    xorg-kbproto:     1.0.7-h14c3975_1002           conda-forge
    xorg-libice:      1.0.9-h516909a_1004           conda-forge
    xorg-libsm:       1.2.3-h84519dc_1000           conda-forge
    xorg-libx11:      1.6.7-h14c3975_1000           conda-forge
    xorg-libxau:      1.0.9-h14c3975_0              conda-forge
    xorg-libxdmcp:    1.1.3-h516909a_0              conda-forge
    xorg-libxext:     1.3.4-h516909a_0              conda-forge
    xorg-libxrender:  0.9.10-h516909a_1002          conda-forge
    xorg-libxt:       1.2.0-h516909a_0              conda-forge
    xorg-renderproto: 0.11.1-h14c3975_1002          conda-forge
    xorg-xextproto:   7.3.0-h14c3975_1002           conda-forge
    xorg-xproto:      7.0.31-h14c3975_1007          conda-forge
    xz:               5.2.4-h14c3975_1001           conda-forge
    zlib:             1.2.11-h14c3975_1004          conda-forge
    zstd:             1.4.0-h3b9ef0a_0              conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... 
ClobberWarning: Conda was asked to clobber an existing path.
  source path: /opt/conda/pkgs/ncurses-6.1-hf484d3e_1002/share/terminfo/2/2621a
  target path: /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/share/terminfo/2/2621a




ClobberWarning: Conda was asked to clobber an existing path.
  source path: /opt/conda/pkgs/ncurses-6.1-hf484d3e_1002/share/terminfo/e/eterm
  target path: /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/share/terminfo/e/eterm




ClobberWarning: Conda was asked to clobber an existing path.
  source path: /opt/conda/pkgs/ncurses-6.1-hf484d3e_1002/share/terminfo/e/eterm-color
  target path: /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/share/terminfo/e/eterm-color

[etc. etc.]

ClobberWarning: Conda was asked to clobber an existing path.
  source path: None
  target path: /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/OpenGL/raw/__pycache__/__init__.cpython-36.pyc




ClobberWarning: Conda was asked to clobber an existing path.
  source path: None
  target path: /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/OpenGL/__pycache__/version.cpython-36.pyc




ClobberWarning: Conda was asked to clobber an existing path.
  source path: None
  target path: /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/OpenGL/__pycache__/wrapper.cpython-36.pyc



done
export PREFIX=/home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/gpi_1561581965783/test_tmp
import: 'gpi'
GPI 1.0.6 (2019-06-26)  Copyright (C) 2014 Dignity Health
This program comes with ABSOLUTELY NO WARRANTY; see the LICENSE for details.

    NO CLINICAL USE.  THE SOFTWARE IS NOT INTENDED FOR COMMERCIAL PURPOSES
AND SHOULD BE USED ONLY FOR NON-COMMERCIAL RESEARCH PURPOSES.  THE SOFTWARE
MAY NOT IN ANY EVENT BE USED FOR ANY CLINICAL OR DIAGNOSTIC PURPOSES.  YOU
ACKNOWLEDGE AND AGREE THAT THE SOFTWARE IS NOT INTENDED FOR USE IN ANY HIGH
RISK OR STRICT LIABILITY ACTIVITY, INCLUDING BUT NOT LIMITED TO LIFE SUPPORT
OR EMERGENCY MEDICAL OPERATIONS OR USES.  LICENSOR MAKES NO WARRANTY AND HAS
NO LIABILITY ARISING FROM ANY USE OF THE SOFTWARE IN ANY HIGH RISK OR STRICT
LIABILITY ACTIVITIES.

Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/gpi_1561581965783/test_tmp/run_test.py", line 2, in <module>
    import gpi
  File "/home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/gpi/__init__.py", line 91, in <module>
    from .widgets import *
  File "/home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/gpi/widgets.py", line 34, in <module>
    QtWebKit = Qimport("QtWebKit")
  File "/home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/gpi/qtapi.py", line 48, in import_module
    p = __import__('PyQt4', globals(), locals(), [moduleName], 0)
ImportError: libQtWebKit.so.4: cannot open shared object file: No such file or directory
Tests failed for gpi-1.0.6-py36_1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for gpi-1.0.6-py36_1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING conda_build.build:tests_failed(2200): Tests failed for gpi-1.0.6-py36_1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: gpi-1.0.6-py36_1.tar.bz2
```
</details>

Here's a diff of the packages installed during testing. Left is the current (breaking) version and right is the output from Azure earlier this week.

![image](https://user-images.githubusercontent.com/48920868/60215088-85115780-982c-11e9-882f-604bbd3108f2.png)

**Comment by msarahan** [comment] 2019-06-26 21:56
Qt is a C++ library and is extremely sensitive to binary compatibility.  I think the most important part of your diff is that qt has switched from conda-forge to defaults.  That's very concerning.  The solver has done this to make something else satisfiable - something about that build from defaults makes it easier to satisfy something else.

The simplest thing to do is to make sure that you are using strict channel priority.

CC @ocefpaf - what's the best way for people to enable strict on their recipes?

**Comment by ocefpaf** [comment] 2019-06-26 22:23
> CC @ocefpaf - what's the best way for people to enable strict on their recipes?

There is not an easy way. (We should really starting using `strict` globally on conda-forge!)

We can "hack" the configure scripts but a new re-render will remove that. I can do that for you early tomorrow @borupdaniel.

**Comment by jakirkham** [comment] 2019-06-27 05:26
Could also copy over the `run_conda_forge_build_setup_*` files from [the `conda-forge-ci-setup` feedstock]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/tree/master/recipe ) into the `recipe` and add that `strict` setting in those files. This would remain even after a re-rendering. Just would need to remember to remove those files once they are not needed any more.

**Comment by borupdaniel** [comment] 2019-06-27 12:11
Thanks for the fast replies! Just to clarify, in the diff, the left column with conda-forge providing qt is the test that fails. On the right is the successful test Monday where defaults was used. I will give the strict channel priorities a try but given that everything in the left column is coming from conda-forge I'm not sure this will resolve the issue.

**Comment by mariusvniekerk** [comment] 2019-06-27 13:08
So there are some other issues with this recipe.  Conda-forge no longer support python 3.4 or 3.5  so much of the stack you are building for does not exist anymore.  
This may very well also be caused by the dependency on qt4 instead of 5.  I'm not entirely sure how healthy our qt4 situation is, but I know it is a lot less healthy than qt5.

**Comment by mariusvniekerk** [comment] 2019-06-27 13:33
I've attempted to make an update pyqt with qt4 in https://github.com/conda-forge/pyqt-feedstock/pull/55, but not holding out much hope for it actually working

**Comment by borupdaniel** [comment] 2019-06-27 14:08
Thanks @marius! I appreciate the clarification on 3.4/3.5 — I was starting to catch on to this while working on an updated build recipe, which is when I ran into the issues described in this thread. I'll try running another build and see if your new update is helpful!

We have a new version with qt5 support almost ready to release, so it seems in the worst case that may be a solution too.

**Comment by aganders3** [comment] 2019-06-27 15:15
> We have a new version with qt5 support almost ready to release, so it seems in the worst case that may be a solution too.

It's looking more and more like this needs to be part of the solution, to me. The flexibility of qtpy is nice but in general Qt4 support is going to keep getting worse so the real benefit of the update is just Qt5 support.

**Comment by mariusvniekerk** [comment] 2019-06-28 13:33
Yeah I would strongly recommend moving to qt5.  Qt4 has been eol since Dec 2015 so I'm not sure it's worth the considerable effort getting it building again.

**Closed as completed** 2019-07-11 17:33 UTC
